tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "github/bootstrap"
tap "caskroom/cask"
brew "git"
brew "jq"
brew "jsonlint"
brew "mas"
# brew "exa"
# brew "openssl"
# brew "python3"
# brew "grc"
# brew "hub"
# brew "imagemagick"
# brew "libyaml"
# brew "nginx", restart_service: true
# brew "nodenv"
# brew "postgresql", restart_service: true
# brew "redis", restart_service: true
# brew "wget"
cask "google-chrome"
cask "textmate"
# cask "1password-cli"
# cask "appcleaner"
# cask "fork"
# cask "keepingyouawake"
# cask "transmission"
# cask "zoomus"
# mas "1Password", id: 443987910
mas "Xcode", id: 497799835
